import { ref } from 'vue'

export type Locale = 'zh-CN' | 'en'

const STORAGE_KEY = 'codex-web-mobile.locale.v1'

function loadLocale(): Locale {
  if (typeof window === 'undefined') return 'zh-CN'
  const saved = window.localStorage.getItem(STORAGE_KEY)
  if (saved === 'en' || saved === 'zh-CN') return saved
  return 'zh-CN'
}

export const currentLocale = ref<Locale>(loadLocale())

const dictionary: Record<Locale, Record<string, string>> = {
  'zh-CN': {
    'appearance.title': '界面风格', 'appearance.codex': 'Codex 清爽', 'appearance.comet': 'Comet 柔和', 'appearance.midnight': '夜间工作台',
    'conversation.title': '当前对话', 'conversation.copyAll': '复制整段对话',
    'balance.provider': 'Provider', 'balance.refresh': '刷新余额',
    'app.newThread': '新会话', 'app.skills': '技能', 'app.settings': '设置', 'app.integrations': '插件与 MCP', 'app.browser': '浏览器', 'app.automations': '自动化',
    'app.workspace': 'Codex 工作区', 'app.server': '本地 app-server', 'app.chat': '对话', 'app.new': '新建会话',
    'app.recent': '最近会话', 'app.untitled': '未命名会话', 'app.noThreads': '还没有会话', 'app.locale': '界面语言',
    'app.openNavigation': '打开导航', 'app.closeNavigation': '关闭导航', 'app.primaryNavigation': '主导航', 'app.local': '本机', 'app.sessionMode': '会话模式', 'app.oneTap': '点击后填入输入框', 'app.thread': '会话', 'app.searchThreads': '搜索会话',
    'status.idle': '空闲', 'status.working': '工作中', 'status.waiting': '等待操作', 'status.failed': '失败', 'status.completed': '已完成',
    'stats.threadTokens': '本会话 token', 'stats.localTokens': '本机累计 token', 'stats.working': '累计工作时长', 'stats.turns': '轮次', 'stats.turnDuration': '本轮用时', 'stats.turnTokens': '本轮 token', 'stats.turnOutput': '本轮输出', 'stats.outputSpeed': '平均输出速度', 'stats.tokensPerSecond': 'token/秒',
    'turn.noActiveId': '没有找到活动任务 ID，已清除过期的思考状态。',
    'mode.default': '默认', 'mode.plan': '计划', 'home.eyebrow': '开始工作', 'home.title': '这次要处理什么？',
    'home.subtitle': '选择工作目录，描述目标，Codex 会在这里展示计划、执行过程和改动。', 'home.workspace': '工作目录', 'home.chooseFolder': '选择目录',
    'home.quickStart': '快速开始', 'home.explore': '了解项目结构', 'home.fix': '定位并修复问题', 'home.review': '检查最近改动',
    'home.exploreHint': '先梳理目录和关键模块', 'home.fixHint': '分析错误并提出修复', 'home.reviewHint': '检查差异和潜在风险',
    'home.promptExplore': '请先梳理这个项目的目录结构、核心模块和主要运行流程。', 'home.promptFix': '请检查当前项目中最明显的问题，先说明原因和修复方案，再实施修复。', 'home.promptReview': '请检查当前工作区最近的代码改动，按严重程度指出问题和风险。',
    'home.recentWork': '最近工作区', 'home.selectHint': '先选择目录，再输入任务。', 'home.activeSessions': '正在运行的会话',
    'inspector.eyebrow': '会话监控', 'inspector.session': '运行概览', 'inspector.context': '上下文占用', 'inspector.used': '已使用', 'inspector.tokens': 'Token 用量',
    'inspector.input': '输入', 'inspector.output': '输出', 'inspector.reasoning': '推理', 'inspector.cached': '缓存输入', 'inspector.run': '本次运行', 'inspector.state': '状态', 'inspector.workingTime': '工作时长', 'inspector.turnCount': '任务轮次', 'inspector.model': '模型配置', 'inspector.skills': '本次使用技能', 'inspector.noUsage': '暂无本地用量记录',
    'effort.none': '无', 'effort.minimal': '极低', 'effort.low': '低', 'effort.medium': '中', 'effort.high': '高', 'effort.xhigh': '超高',
    'activity.thinking': '思考中', 'activity.writing': '正在组织回答', 'activity.runningCommand': '正在运行命令', 'activity.changingFiles': '正在修改文件', 'activity.commandOutput': '命令输出', 'activity.updatingChanges': '正在更新改动', 'activity.waiting': '等待你的确认', 'activity.question': '等待你的回答', 'activity.resolved': '已处理', 'activity.runningTool': '正在调用工具', 'activity.planUpdated': '更新执行计划', 'activity.completed': '已完成', 'activity.failed': '运行失败', 'activity.title': '工作动态', 'activity.open': '打开工作动态', 'activity.close': '关闭工作动态', 'activity.noEvents': '暂时没有新的事件。', 'activity.progressSummary': '进展摘要', 'activity.model': '模型', 'activity.reasoning': '推理强度', 'activity.worked': '工作了',
    'plan.title': '执行计划', 'plan.changes': '文件改动', 'settings.eyebrow': '运行环境', 'settings.title': '设置', 'settings.subtitle': '连接模型服务，调整运行方式和 Codex 配置。',
    'settings.connection': '模型连接', 'settings.runtime': '运行设置', 'settings.toml': '高级配置', 'settings.provider': '服务提供方名称', 'settings.baseUrl': 'API 地址',
    'balance.title': '余额查询', 'balance.preset': '接口预设', 'balance.custom': '自定义接口', 'balance.endpoint': '余额接口 URL', 'balance.endpointPlaceholder': '完整地址，或相对当前 Provider 的路径', 'balance.totalPath': '余额/总额字段路径', 'balance.totalPathPlaceholder': '例如 data.balance', 'balance.usedPath': '已用金额字段路径', 'balance.usedPathPlaceholder': '可选，例如 data.total_usage', 'balance.currencyPath': '币种字段路径', 'balance.currencyPathPlaceholder': '可选，例如 data.currency', 'balance.currencyFallback': '默认币种', 'balance.authHeader': '认证请求头', 'balance.authPrefix': '认证前缀', 'balance.credentialNotice': '使用已保存的当前 Provider API Key；密钥只由本机后端读取。接口需与 Provider 同源。', 'balance.query': '查询余额', 'balance.checking': '查询中…', 'balance.remaining': '可用余额', 'balance.total': '总额', 'balance.used': '已使用', 'balance.saveSettings': '保存查询设置', 'balance.saved': '余额查询设置已保存。', 'balance.saveFailed': '无法保存余额查询设置。', 'balance.queryFailed': '余额查询失败。',
    'settings.apiKey': 'API Key', 'settings.model': '默认模型', 'settings.wireApi': '接口协议', 'settings.responses': 'Responses', 'settings.chat': 'Chat Completions',
    'settings.listen': '网页监听范围', 'settings.localOnly': '仅本机', 'settings.lan': '允许局域网设备', 'settings.port': '网页端口', 'settings.effort': '推理强度',
    'settings.contextWindow': '上下文窗口', 'settings.personality': '表达风格', 'settings.save': '保存设置', 'settings.saving': '保存中…', 'settings.hide': '隐藏',
    'settings.show': '显示', 'settings.revealKey': '从 auth.json 读取密钥', 'settings.authSource': '密钥来源', 'settings.authEditHint': '修改后点击保存设置写回 auth.json', 'settings.validate': '检查格式', 'settings.saveToml': '保存 TOML', 'settings.chooseBackup': '选择备份',
    'settings.restore': '恢复备份', 'settings.notice': '保存后会重启 Codex app-server，新设置用于后续请求。', 'settings.savedMessage': '设置已保存；新配置将在后续请求中生效。', 'settings.tomlValid': 'TOML 格式正确。', 'settings.tomlSaved': 'TOML 已保存；app-server 会在下次请求时重启。', 'settings.backupRestored': '配置备份已恢复。', 'settings.restartConfirm': '确定按这些设置重启网页服务吗？', 'settings.restarting': '网页服务正在重启；如修改了端口，请使用新地址重新连接。',
    'skills.eyebrow': '能力管理', 'skills.title': '技能', 'skills.subtitle': '安装技能，并选择要带入新会话的能力。', 'skills.source': 'GitHub、npm、URL 或本机路径',
    'skills.name': '名称（可选）', 'skills.install': '安装技能', 'skills.installing': '安装中…', 'skills.enable': '启用', 'skills.disable': '停用', 'skills.delete': '删除', 'skills.search': '搜索技能', 'skills.selectAll': '全选', 'skills.clearAll': '清空选择', 'skills.selectedCount': '项已选', 'skills.noMatches': '没有匹配的技能',
    'skills.empty': '尚未安装技能。', 'skills.selected': '已选技能', 'skills.confirmInstall': '确认从此来源安装技能？', 'skills.confirmDelete': '确认删除此技能？', 'skills.installed': '技能已安装。',
    'integrations.eyebrow': '扩展能力', 'integrations.title': '插件与 MCP', 'integrations.subtitle': '查看已安装插件和 MCP 服务连接状态。', 'integrations.uninstalled': '插件已卸载。',
    'integrations.refresh': '刷新状态', 'integrations.install': '安装插件', 'integrations.plugins': '插件', 'integrations.servers': 'MCP 服务', 'integrations.installRequested': '已提交插件安装请求。',
    'integrations.emptyPlugins': '没有可显示的插件。', 'integrations.emptyServers': '没有 MCP 服务状态。', 'integrations.uninstall': '卸载', 'integrations.pluginName': '输入插件名称或市场标识',
    'browser.eyebrow': '网页工具', 'browser.title': '浏览器', 'browser.subtitle': '在工作区中打开网页；模型的工具调用和工作状态仍显示在会话中。', 'browser.placeholder': '输入网址', 'browser.open': '打开网页', 'browser.loading': '正在载入网页…', 'browser.embedNotice': '部分网站会禁止嵌入显示，可在浏览器中打开。', 'browser.openExternal': '外部打开', 'browser.invalidUrl': '请输入有效的 HTTP 或 HTTPS 地址。', 'browser.empty': '输入 HTTP 或 HTTPS 网址后在此查看。',
    'files.title': '选择文件', 'files.close': '关闭文件选择器', 'files.open': '打开目录', 'files.upload': '上传文件', 'files.home': '主目录', 'files.folder': '文件夹', 'files.file': '文件', 'files.empty': '此目录为空。', 'files.previewTruncated': '预览内容已截断', 'files.remove': '移除附件', 'files.path': '目录路径',
    'composer.placeholder': '描述任务；输入 / 搜索命令', 'composer.noThread': '先选择或新建会话', 'composer.files': '添加文件', 'composer.model': '模型', 'composer.thinking': '推理', 'composer.send': '发送消息', 'composer.stop': '停止运行', 'composer.guide': '追加引导', 'composer.stopAndSend': '停止并发送', 'composer.guideHint': '把补充要求追加到当前任务', 'composer.stopAndSendHint': '停止当前任务后开始新任务',
    'conversation.loading': '正在载入会话…', 'conversation.empty': '这个会话还没有消息。', 'conversation.displaySettings': '消息显示设置', 'conversation.showAll': '全部显示', 'conversation.hideAll': '全部隐藏', 'conversation.noTypes': '暂无消息类型', 'conversation.pastedContent': '粘贴内容', 'conversation.chars': '字符', 'conversation.expandPasted': '展开粘贴内容', 'conversation.collapsePasted': '收起粘贴内容', 'message.copy': '复制消息', 'message.copyCode': '复制代码', 'message.copied': '已复制', 'message.editResend': '编辑并重发', 'request.accept': '允许一次', 'request.acceptSession': '本会话始终允许', 'request.decline': '拒绝', 'request.cancel': '取消',
    'request.other': '填写其他答案', 'request.submit': '提交答案', 'request.failTool': '拒绝工具调用', 'request.emptySuccess': '返回空结果', 'request.returnEmpty': '返回空响应', 'request.reject': '拒绝请求', 'request.number': '请求', 'request.previewImage': '消息图片预览', 'request.expandedImage': '放大后的图片', 'request.installSkill': '确认从此来源安装技能？', 'request.deleteSkill': '确认删除此技能？', 'request.deletePlugin': '确认卸载此插件？',
    'command.title': '命令面板', 'command.search': '搜索命令', 'command.plan': '计划模式', 'command.skills': '打开技能', 'command.mcp': '打开插件与 MCP', 'command.settings': '打开设置', 'command.model': '切换模型', 'command.status': '查看会话状态', 'command.context': '查看上下文用量', 'command.browser': '打开浏览器',
    'command.planDescription': '为下一条任务启用先规划后执行。', 'command.skillsDescription': '管理并选择本机会话技能。', 'command.mcpDescription': '查看 MCP 服务和插件连接。', 'command.settingsDescription': '配置模型、Provider 和 config.toml。', 'command.statusDescription': '查看本会话运行状态和耗时。', 'command.contextDescription': '查看当前上下文和累计 token。', 'command.browserDescription': '在工作区内打开网页。',
    'slash.plan': '切换到计划模式', 'slash.review': '检查当前改动并指出风险', 'slash.explore': '梳理项目结构和关键模块', 'slash.skills': '打开技能管理', 'slash.mcp': '查看插件和 MCP 服务', 'slash.browser': '打开内置浏览器', 'slash.settings': '打开 Codex 设置', 'slash.status': '查看本机会话状态', 'slash.context': '查看上下文与 token 用量', 'slash.model': '切换当前模型',
    'slash.navigate': '上下移动', 'slash.choose': '选择', 'slash.close': '关闭', 'slash.contextPanel': '当前上下文和 Token 用量', 'slash.modelPanel': '选择模型', 'slash.activeModel': '当前模型',
    'common.open': '打开', 'common.none': '无', 'common.pragmatic': '务实', 'common.friendly': '友好', 'common.unknown': '未知', 'common.installed': '已安装', 'common.working': '工作中',
    'common.default': '默认', 'common.hide': '收起', 'common.show': '显示', 'common.confirm': '确认', 'common.cancel': '取消', 'common.loading': '载入中…', 'common.saved': '已保存', 'common.invalid': '格式无效', 'common.noData': '暂无数据',
    'skills.deleted': '技能已删除。', 'sidebar.renameThread': '重命名会话', 'sidebar.renameThreadDescription': '输入新的会话名称。', 'sidebar.archiveConfirm': '确认归档这个会话吗？', 'sidebar.removeProjectConfirm': '确认移除这个项目分组吗？',
    'sidebar.pin': '置顶', 'sidebar.archive': '归档', 'sidebar.threads': '会话', 'sidebar.noMatches': '没有匹配的会话', 'sidebar.loading': '正在载入会话…', 'sidebar.projectMenu': '项目菜单', 'sidebar.editName': '编辑名称', 'sidebar.remove': '移除', 'sidebar.projectName': '项目名称', 'sidebar.rename': '重命名', 'sidebar.noThreads': '没有会话', 'sidebar.showMore': '显示更多', 'sidebar.showLess': '收起更多', 'sidebar.startThread': '新建会话', 'sidebar.expand': '展开侧栏', 'sidebar.collapse': '收起侧栏',
  },
  en: {
    'appearance.title': 'Interface style', 'appearance.codex': 'Codex clean', 'appearance.comet': 'Comet soft', 'appearance.midnight': 'Midnight desk',
    'conversation.title': 'Conversation', 'conversation.copyAll': 'Copy conversation',
    'balance.provider': 'Provider', 'balance.refresh': 'Refresh balance',
    'app.newThread': 'New thread', 'app.skills': 'Skills', 'app.settings': 'Settings', 'app.integrations': 'Plugins & MCP', 'app.browser': 'Browser', 'app.automations': 'Automations',
    'app.workspace': 'Codex workspace', 'app.server': 'Local app-server', 'app.chat': 'Chat', 'app.new': 'New thread',
    'app.recent': 'Recent threads', 'app.untitled': 'Untitled thread', 'app.noThreads': 'No threads yet', 'app.locale': 'Language',
    'app.openNavigation': 'Open navigation', 'app.closeNavigation': 'Close navigation', 'app.primaryNavigation': 'Primary navigation', 'app.local': 'Local', 'app.sessionMode': 'Session mode', 'app.oneTap': 'Click to add to composer', 'app.thread': 'Thread', 'app.searchThreads': 'Search conversations',
    'status.idle': 'Idle', 'status.working': 'Working', 'status.waiting': 'Waiting', 'status.failed': 'Failed', 'status.completed': 'Completed',
    'stats.threadTokens': 'thread tokens', 'stats.localTokens': 'local tokens', 'stats.working': 'total working', 'stats.turns': 'turns', 'stats.turnDuration': 'turn time', 'stats.turnTokens': 'turn tokens', 'stats.turnOutput': 'turn output', 'stats.outputSpeed': 'avg output speed', 'stats.tokensPerSecond': 'tokens/s',
    'turn.noActiveId': 'No active turn ID was available; the stale thinking state was cleared.',
    'mode.default': 'Default', 'mode.plan': 'Plan', 'home.eyebrow': 'Start working', 'home.title': 'What are we working on?',
    'home.subtitle': 'Choose a workspace and describe the goal. Plans, execution and changes appear here.', 'home.workspace': 'Workspace', 'home.chooseFolder': 'Choose folder',
    'home.quickStart': 'Quick start', 'home.explore': 'Explore this project', 'home.fix': 'Find and fix an issue', 'home.review': 'Review recent changes',
    'home.exploreHint': 'Map folders and key modules', 'home.fixHint': 'Analyze a bug and propose a fix', 'home.reviewHint': 'Inspect the diff and risks',
    'home.promptExplore': 'Map this project: explain its folder structure, key modules and main execution flow.', 'home.promptFix': 'Inspect this project for an obvious issue. Explain the cause and fix before making the change.', 'home.promptReview': 'Review the recent changes in this workspace and report issues and risks by severity.',
    'home.recentWork': 'Recent workspaces', 'home.selectHint': 'Choose a workspace before starting a task.', 'home.activeSessions': 'Active sessions',
    'inspector.eyebrow': 'SESSION MONITOR', 'inspector.session': 'Run overview', 'inspector.context': 'Context usage', 'inspector.used': 'used', 'inspector.tokens': 'Token usage',
    'inspector.input': 'Input', 'inspector.output': 'Output', 'inspector.reasoning': 'Reasoning', 'inspector.cached': 'Cached input', 'inspector.run': 'This run', 'inspector.state': 'Status', 'inspector.workingTime': 'Working time', 'inspector.turnCount': 'Turns', 'inspector.model': 'Model setup', 'inspector.skills': 'Skills in this run', 'inspector.noUsage': 'No local usage recorded yet',
    'effort.none': 'None', 'effort.minimal': 'Minimal', 'effort.low': 'Low', 'effort.medium': 'Medium', 'effort.high': 'High', 'effort.xhigh': 'Extra high',
    'activity.thinking': 'Thinking', 'activity.writing': 'Writing response', 'activity.runningCommand': 'Running command', 'activity.changingFiles': 'Changing files', 'activity.commandOutput': 'Command output', 'activity.updatingChanges': 'Updating changes', 'activity.waiting': 'Waiting for your decision', 'activity.question': 'Waiting for your answer', 'activity.resolved': 'Resolved', 'activity.runningTool': 'Calling a tool', 'activity.planUpdated': 'Updated the plan', 'activity.completed': 'Completed', 'activity.failed': 'Run failed', 'activity.title': 'Activity', 'activity.open': 'Open activity', 'activity.close': 'Close activity', 'activity.noEvents': 'No recent events.', 'activity.progressSummary': 'Progress summary', 'activity.model': 'Model', 'activity.reasoning': 'Reasoning', 'activity.worked': 'Worked for',
    'plan.title': 'Plan', 'plan.changes': 'File changes', 'settings.eyebrow': 'Runtime', 'settings.title': 'Settings', 'settings.subtitle': 'Configure your model provider, runtime and Codex preferences.',
    'settings.connection': 'Model connection', 'settings.runtime': 'Runtime', 'settings.toml': 'Advanced config', 'settings.provider': 'Provider name', 'settings.baseUrl': 'Base URL',
    'balance.title': 'Balance', 'balance.preset': 'Provider preset', 'balance.custom': 'Custom endpoint', 'balance.endpoint': 'Balance endpoint URL', 'balance.endpointPlaceholder': 'Full URL or a path on the active provider origin', 'balance.totalPath': 'Balance/total JSON path', 'balance.totalPathPlaceholder': 'For example, data.balance', 'balance.usedPath': 'Used amount JSON path', 'balance.usedPathPlaceholder': 'Optional, for example, data.total_usage', 'balance.currencyPath': 'Currency JSON path', 'balance.currencyPathPlaceholder': 'Optional, for example, data.currency', 'balance.currencyFallback': 'Default currency', 'balance.authHeader': 'Authorization header', 'balance.authPrefix': 'Authorization prefix', 'balance.credentialNotice': 'Uses the saved API key for the active provider. The key stays on the local server; the endpoint must share the provider origin.', 'balance.query': 'Check balance', 'balance.checking': 'Checking…', 'balance.remaining': 'Available balance', 'balance.total': 'Total', 'balance.used': 'Used', 'balance.saveSettings': 'Save query settings', 'balance.saved': 'Balance query settings saved.', 'balance.saveFailed': 'Could not save balance query settings.', 'balance.queryFailed': 'Balance query failed.',
    'settings.apiKey': 'API key', 'settings.model': 'Default model', 'settings.wireApi': 'API protocol', 'settings.responses': 'Responses', 'settings.chat': 'Chat completions',
    'settings.listen': 'Web server binding', 'settings.localOnly': 'This device only', 'settings.lan': 'Allow local network', 'settings.port': 'Web port', 'settings.effort': 'Reasoning effort',
    'settings.contextWindow': 'Context window', 'settings.personality': 'Personality', 'settings.save': 'Save settings', 'settings.saving': 'Saving…', 'settings.hide': 'Hide',
    'settings.show': 'Show', 'settings.revealKey': 'Read key from auth.json', 'settings.authSource': 'Key source', 'settings.authEditHint': 'Edit it, then save settings to write auth.json', 'settings.validate': 'Validate', 'settings.saveToml': 'Save TOML', 'settings.chooseBackup': 'Choose backup',
    'settings.restore': 'Restore backup', 'settings.notice': 'Saving restarts Codex app-server. New settings apply to subsequent requests.', 'settings.savedMessage': 'Settings saved. New values apply to subsequent requests.', 'settings.tomlValid': 'TOML is valid.', 'settings.tomlSaved': 'TOML saved. app-server will restart on the next request.', 'settings.backupRestored': 'Configuration backup restored.', 'settings.restartConfirm': 'Restart the web server with these runtime settings?', 'settings.restarting': 'Web server is restarting. Reconnect at the new address if the port changed.',
    'skills.eyebrow': 'Capabilities', 'skills.title': 'Skills', 'skills.subtitle': 'Install skills and choose which capabilities to include in new sessions.', 'skills.source': 'GitHub, npm, URL or local path',
    'skills.name': 'Name (optional)', 'skills.install': 'Install skill', 'skills.installing': 'Installing…', 'skills.enable': 'Enable', 'skills.disable': 'Disable', 'skills.delete': 'Delete', 'skills.search': 'Search skills', 'skills.selectAll': 'Select all', 'skills.clearAll': 'Clear selection', 'skills.selectedCount': 'selected', 'skills.noMatches': 'No matching skills',
    'skills.empty': 'No skills installed.', 'skills.selected': 'Selected skills', 'skills.confirmInstall': 'Install a skill from this source?', 'skills.confirmDelete': 'Delete this skill?', 'skills.installed': 'Skill installed.',
    'integrations.eyebrow': 'Extensions', 'integrations.title': 'Plugins & MCP', 'integrations.subtitle': 'Inspect installed plugins and MCP server connections.', 'integrations.uninstalled': 'Plugin uninstalled.',
    'integrations.refresh': 'Refresh status', 'integrations.install': 'Install plugin', 'integrations.plugins': 'Plugins', 'integrations.servers': 'MCP servers', 'integrations.installRequested': 'Plugin installation requested.',
    'integrations.emptyPlugins': 'No plugin metadata available.', 'integrations.emptyServers': 'No MCP server status available.', 'integrations.uninstall': 'Uninstall', 'integrations.pluginName': 'Plugin name or marketplace identifier',
    'browser.eyebrow': 'Web tool', 'browser.title': 'Browser', 'browser.subtitle': 'Open a page in the workspace. Tool activity remains visible in the session.', 'browser.placeholder': 'Enter a URL', 'browser.open': 'Open page', 'browser.loading': 'Loading page…', 'browser.embedNotice': 'Some sites block embedded pages; open them in the browser instead.', 'browser.openExternal': 'Open externally', 'browser.invalidUrl': 'Enter a valid HTTP or HTTPS URL.', 'browser.empty': 'Enter an HTTP or HTTPS URL to view it here.',
    'files.title': 'Select files', 'files.close': 'Close file picker', 'files.open': 'Open folder', 'files.upload': 'Upload', 'files.home': 'Home directory', 'files.folder': 'Folder', 'files.file': 'File', 'files.empty': 'This directory is empty.', 'files.previewTruncated': 'Preview truncated', 'files.remove': 'Remove attachment', 'files.path': 'Directory path',
    'composer.placeholder': 'Describe a task; type / for commands', 'composer.noThread': 'Select or create a thread first', 'composer.files': 'Add files', 'composer.model': 'Model', 'composer.thinking': 'Reasoning', 'composer.send': 'Send message', 'composer.stop': 'Stop run', 'composer.guide': 'Add guidance', 'composer.stopAndSend': 'Stop & send', 'composer.guideHint': 'Append this to the active task', 'composer.stopAndSendHint': 'Stop this run, then start a new task',
    'conversation.loading': 'Loading thread…', 'conversation.empty': 'This thread has no messages yet.', 'conversation.displaySettings': 'Message display settings', 'conversation.showAll': 'Show all', 'conversation.hideAll': 'Hide all', 'conversation.noTypes': 'No message types yet', 'conversation.pastedContent': 'Pasted Content', 'conversation.chars': 'chars', 'conversation.expandPasted': 'Expand pasted content', 'conversation.collapsePasted': 'Collapse pasted content', 'message.copy': 'Copy message', 'message.copyCode': 'Copy code', 'message.copied': 'Copied', 'message.editResend': 'Edit and resend', 'request.accept': 'Allow once', 'request.acceptSession': 'Always allow this session', 'request.decline': 'Decline', 'request.cancel': 'Cancel',
    'request.other': 'Other answer', 'request.submit': 'Submit answers', 'request.failTool': 'Reject tool call', 'request.emptySuccess': 'Return empty result', 'request.returnEmpty': 'Return empty response', 'request.reject': 'Reject request', 'request.number': 'Request', 'request.previewImage': 'Message image preview', 'request.expandedImage': 'Expanded image', 'request.installSkill': 'Install a skill from this source?', 'request.deleteSkill': 'Delete this skill?', 'request.deletePlugin': 'Uninstall this plugin?',
    'command.title': 'Command palette', 'command.search': 'Search commands', 'command.plan': 'Plan mode', 'command.skills': 'Open skills', 'command.mcp': 'Open plugins & MCP', 'command.settings': 'Open settings', 'command.model': 'Change model', 'command.status': 'Show session status', 'command.context': 'Show context usage', 'command.browser': 'Open browser',
    'command.planDescription': 'Plan before execution on the next task.', 'command.skillsDescription': 'Manage and select local session skills.', 'command.mcpDescription': 'Inspect MCP servers and plugin connections.', 'command.settingsDescription': 'Configure models, providers and config.toml.', 'command.statusDescription': 'Inspect session state and working time.', 'command.contextDescription': 'View current context and cumulative tokens.', 'command.browserDescription': 'Open a web page in the workspace.',
    'slash.plan': 'Switch to plan mode', 'slash.review': 'Review current changes and identify risks', 'slash.explore': 'Map the project structure and key modules', 'slash.skills': 'Open skill management', 'slash.mcp': 'Inspect plugins and MCP servers', 'slash.browser': 'Open the built-in browser', 'slash.settings': 'Open Codex settings', 'slash.status': 'Show local session status', 'slash.context': 'Show context and token usage', 'slash.model': 'Change the active model',
    'slash.navigate': 'Navigate', 'slash.choose': 'Choose', 'slash.close': 'Close', 'slash.contextPanel': 'Current context and token usage', 'slash.modelPanel': 'Select a model', 'slash.activeModel': 'Active model',
    'common.open': 'Open', 'common.none': 'None', 'common.pragmatic': 'Pragmatic', 'common.friendly': 'Friendly', 'common.unknown': 'Unknown', 'common.installed': 'Installed', 'common.working': 'Working',
    'common.default': 'Default', 'common.hide': 'Hide', 'common.show': 'Show', 'common.confirm': 'Confirm', 'common.cancel': 'Cancel', 'common.loading': 'Loading…', 'common.saved': 'Saved', 'common.invalid': 'Invalid format', 'common.noData': 'No data yet',
    'skills.deleted': 'Skill deleted.', 'sidebar.renameThread': 'Rename thread', 'sidebar.renameThreadDescription': 'Enter a new conversation name.', 'sidebar.archiveConfirm': 'Archive this conversation?', 'sidebar.removeProjectConfirm': 'Remove this project group?',
    'sidebar.pin': 'Pin', 'sidebar.archive': 'Archive', 'sidebar.threads': 'Threads', 'sidebar.noMatches': 'No matching threads', 'sidebar.loading': 'Loading threads…', 'sidebar.projectMenu': 'Project menu', 'sidebar.editName': 'Edit name', 'sidebar.remove': 'Remove', 'sidebar.projectName': 'Project name', 'sidebar.rename': 'Rename', 'sidebar.noThreads': 'No threads', 'sidebar.showMore': 'Show more', 'sidebar.showLess': 'Show less', 'sidebar.startThread': 'Start new thread', 'sidebar.expand': 'Expand sidebar', 'sidebar.collapse': 'Collapse sidebar',
  },
}

export function useLocale() {
  function setLocale(next: Locale): void {
    currentLocale.value = next
    if (typeof window !== 'undefined') window.localStorage.setItem(STORAGE_KEY, next)
    document.documentElement.lang = next === 'zh-CN' ? 'zh-CN' : 'en'
  }

  function t(key: string): string {
    return dictionary[currentLocale.value][key] || dictionary.en[key] || key
  }

  return { locale: currentLocale, setLocale, t }
}
